version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ikk5515/app/KoreanTraining_Baleum/
    overwrite: yes
# file_exists_behavior : OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ikk5515
    group: ikk5515

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ikk5515
